# Generated by Django 3.2.6 on 2024-11-13 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hash',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('hash', models.CharField(max_length=1000)),
            ],
        ),
    ]
