version: '3.8'

services:
  # Coordinador (votaci칩n principal)
  coordinador:
    build: ./coordinador
    ports:
      - "8081:8080"  # Mapea el puerto 8081 en tu m치quina al puerto 8080 en el contenedor
    environment:
      # Definir las URLs de los nodos en la variable de entorno NODES
      - NODES=http://gestorEstudiante1:8080/disponibilidad,http://gestorEstudiante2:8080/disponibilidad,http://gestorEstudiante3:8080/disponibilidad
    depends_on:
      - gestorEstudiante1
      - gestorEstudiante2
      - gestorEstudiante3
    networks:
      - app_network

  # Nodo 1 (primera instancia del gestor de estudiantes)
  gestorEstudiante1:
    build: ./gestorEstudiante
    ports:
      - "8082:8080"  
    networks:
      - app_network

  # Nodo 2 (segunda instancia del gestor de estudiantes)
  gestorEstudiante2:
    build: ./gestorEstudiante
    ports:
      - "8083:8080"  # Mapea el puerto 8083 en tu m치quina al puerto 8080 en el contenedor
    networks:
      - app_network

  # Nodo 3 (tercera instancia del gestor de estudiantes)
  gestorEstudiante3:
    build: ./gestorEstudiante
    ports:
      - "8084:8080"  # Mapea el puerto 8084 en tu m치quina al puerto 8080 en el contenedor
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

