# Generated by Django 3.2.6 on 2024-10-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('tipo', models.CharField(max_length=2)),
                ('idEstudiante', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
