# Generated by Django 3.2.6 on 2024-10-17 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestorEstudiante', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='curso',
            new_name='cursos',
        ),
    ]
